# Generated by Django 3.0.5 on 2020-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='suggession_fifth',
            new_name='suggestion_fifth',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='suggession_first',
            new_name='suggestion_first',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='suggession_fourth',
            new_name='suggestion_fourth',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='suggession_second',
            new_name='suggestion_second',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='suggession_seventh',
            new_name='suggestion_seventh',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='suggession_sixth',
            new_name='suggestion_sixth',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='suggession_third',
            new_name='suggestion_third',
        ),
    ]
