# Generated by Django 3.0.5 on 2020-06-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200619_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='video',
        ),
    ]
